# Model arguments
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Chemical Task arguments
chem_task: kinetic_metrics_category
dataset_id_or_path: /work/liac/kinetic
rewards:
- format_continuous
- accuracy
- answer_covered_in_reasoning_traces

save_completions: true

# Training arguments
max_steps: 2000
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 1500
max_completion_length: 5000
num_generations: 4
use_vllm: true
vllm_device: "cuda:3"
vllm_gpu_memory_utilization: 0.8

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- wandb

save_strategy: "steps"
save_steps: 5
seed: 42

# Hugging Face Hub 
push_to_hub: false
