# Model arguments
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Chemical Task arguments
chem_task: rxn_naming
dataset_id_or_path: ${MIST_DATA_DIR}/rxn_naming/reaction_class_prompts_600k.csv
rewards:
- format
- accuracy

# Training arguments
max_steps: 450
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03
beta: 0.001
max_prompt_length: 256
max_completion_length: 2048
num_generations: 8
use_vllm: true
vllm_device: "cuda:3"
vllm_gpu_memory_utilization: 0.7
vllm_max_model_len: 2048

logging_strategy: steps
logging_steps: 2
report_to:
- wandb

save_strategy: "steps"
save_steps: 25
seed: 42
push_to_hub: false
