[tox]
isolated_build = true

envlist =
    lint
    # pyroma
    # mypy
    py


[testenv:lint]
deps =
    black[jupyter]
    isort
    nbqa
skip_install = true
commands =
    black --line-length 79 .
    isort .
    nbqa isort .
description = Run linters.

