[tox]
isolated_build = true

envlist =
    lint
    py


[testenv]
deps =
    -rdev-requirements.txt
setenv =
    PYTHONPATH = {toxinidir}/src
skip_install = true
commands =
    pytest tests src/open_r1/tasks/kinetic_data/tests -q


[testenv:lint]
deps =
    black[jupyter]
    isort
    nbqa
skip_install = true
commands =
    black --check --line-length 119 .
    isort --check-only .
    nbqa isort --check-only .
description = Run linters.
