from flask import Flask, request, jsonify
import gc
import random
from io import StringIO
from pymatgen.core import Structure
from pymatgen.analysis.structure_matcher import StructureMatcher
import gemmi
from pymatgen.io.cif import CifWriter
from AIRS_preporcess._tokenizer import CIFTokenizer
from mace.calculators import mace_mp
from ase.io import read

def compare_internal_energy(cif1, cif2):
    atoms1 = read(StringIO(cif1),format='cif')
    atoms2 = read(StringIO(cif2),format='cif')
    calc = mace_mp(model="large", device='cuda')
    atoms1.calc = calc
    atoms2.calc = calc
    energy1_total = atoms1.get_potential_energy()
    energy2_total = atoms2.get_potential_energy()
    
    energy1_per_atom = energy1_total / len(atoms1)
    energy2_per_atom = energy2_total / len(atoms2)
    print(";;;;;;;;;;;;;;;;;;;;;")
    print("Orginal Internal Energy:", energy1_per_atom)
    print("LLM Energy:", energy2_per_atom)
    print(";;;;;;;;;;;;;;;;;;;;;")
    if energy1_per_atom < energy2_per_atom:
        return -4
    elif energy1_per_atom > energy2_per_atom:
        return 1
    else:
        return -10

app = Flask(__name__)
cif_tokenizer = CIFTokenizer()

def parse_llm_structure(answer_text):
    """
    """
    try:
        return Structure.from_str(answer_text, fmt="cif")
    except Exception as e:
        print("Error in parse_llm_structure:", e)
        return None

def compute_score(answer_text, ground_truth, alpha=5.0):
    """
    Calculate the score based on the structure match:
        Logic description:
        
    """
    try:
        answer_text = cif_tokenizer.deserialize(answer_text, ground_truth.get("ground_truth", ""))
    except Exception as e:
        print("format error 1", e)
        return -10
    do_print = random.randint(1, 1) == 1
    if do_print:
        print("-------------- START ------------------")
        print("answer_text:", answer_text)
        print("ground_cif:", ground_truth.get("ground_truth", ""))
    
    dft_cif = ground_truth.get("ground_truth", "")
    if not dft_cif:
        print("No ground truth CIF content provided.")
        return -10

    try:
        doc = gemmi.cif.read_string(dft_cif)
        doc.check_for_missing_values()
        doc.check_for_duplicates()

        doc = gemmi.cif.read_string(answer_text)
        doc.check_for_missing_values()
        doc.check_for_duplicates()
    except Exception as e:
        print("CIF error:", e)
        return -10

    try:
        dft_structure = Structure.from_str(dft_cif, fmt="cif")
        if do_print:
            print("dft_structure OK")
    except Exception as e:
        if do_print:
            print("Error parsing DFT structure:", e)
        return -10

    try:
        llm_structure = parse_llm_structure(answer_text)
        if llm_structure is None:
            return -10
        if do_print:
            print("llm_structure OK")
    except Exception as e:
        print("Error parsing LLM-generated structure:", e)
        return -10
    reward = -5
    try:
        reward = compare_internal_energy(dft_cif, answer_text)
    except Exception as e:
        print("**************************")
        print('CALC ERROR:', e)
        print("**************************")
        print("-------------- END ------------------")
        return reward

    if do_print:
        print(f"Reward: {reward}")
        print("-------------- END ------------------")
    return reward

@app.route('/compute_score', methods=['POST'])
def compute_score_endpoint():
    """
    The interface /compute_score receives POST requests, and the JSON format content needs to include:
        - answer_text: CIF content string generated by LLM
        - ground_truth: dictionary containing the key "ground_truth", and the value is the CIF content after DFT optimization

        Return the calculation result in JSON format, for example:
        { "reward": -0.123 }
    """
    data = request.get_json()
    if not data:
        return jsonify({"error": "No JSON data provided"}), 400
    
    answer_text = data.get("answer_text", "")
    ground_truth = data.get("ground_truth", {})
    
    if not answer_text or not ground_truth:
        return jsonify({"error": "Missing required fields: answer_text and ground_truth"}), 400
    
    reward = compute_score(answer_text, ground_truth)
    gc.collect()
    return jsonify({"reward": reward})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9001, debug=True)