compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 16
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero_stage: 3
  train_batch_size: 64
  train_micro_batch_size_per_gpu: 4
  bf16:
    enabled: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
rdzv_backend: static
same_network: true
use_cpu: false

